language: java

jdk:
- oraclejdk8
- oraclejdk7
os:
- linux
- windows
- osx

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8
  - os: osx

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2

install: true
# NOTE: Following line can be introduced later
#script: mvn clean versions:set -DnewVersion=0.1.0 verify
script: mvn clean verify
# NOTE: Following line can be introduced later
#after_success: mvn gpg:sign site deploy:deploy assembly:single

# NOTE: Following line can be introduced later
#deploy:
#  provider: releases
#  api_key:
#    secure: FTi6CrTcx1dBGFHoWDp4O81BxJLkFFYVnSZP+z3Q4XvDbaYiA3HyG+tlul6A1XTn/4NzN9hrGoJQxU38PmOJ/F1rToi7Mb00lpv/FDI/bYLkWGHpisrixYo4pTKpqU9GtpnRrVTT4DjNChsha/k0SVgIm7EpBrViKGPvLgRkg4z9iWs6UQaQlNp/1tObsfVy+XFxIG9mtor7BKl3Vnj0HcetFG3cm2zKhp11zwBOcANjfD8O6QfmhSADH5UvFdutn2/p4ch1GcVMxtXxMaqdU7sfeogRWuodHaNfS+rCD3vDBWSg+r60x/MiOJbDiH+Kmh0uKa6c5SRNmRoDCRpsgWXMQ+s85t2XSVjLAqLrFyn+vAw02MpbwsG2ERia/xDnfL0iQXG2eEzdpVeIdOiHTkW/B0pWBqIsu3M9SGPTvUBBXZ0glTP+Pjy7gpjiOLqYEc3XMnE5d4BqIPB+EAGpjkRen1VcWmy2Roweu7marbTfSL1E+Wlo6kGjW/ExGcZuDWEyZb/LprRkxpDQcyt2taOnc+IbFFEmeVGznB1eqz52XnuJYWxTZ6J02nX91r6ZrQ1n+h9laE7Us+hlxi5oweQEd2eSr+gVNdrK4ALY1rHNVpI1apEDwfBTDCRjVDAOLyT8/x2nRjkIuZngHXJCqcNlHoBaR4AUtGFHvVBZMqA=
#  file: target/exitsign-0.1.0.zip
#  skip_cleanup: true
#  on:
#    repo: antonvorobyev/exitsign
#    tags: true
#
#notifications:
#  email:
#    - anton@vorobyev.co